name: Test docker images

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Test capra314cabra/tex:${{ matrix.tag }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tag:
          - "latest"
          - "chem"
          - "chem-jp"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Generate Dockerfile
        run: |
          python ./build.py $PACKAGES_FILE
        env:
          PACKAGES_FILE: ${{ matrix.tag }}
      - name: Copy .latexmkrc
        run: |
          cp ./.latexmkrc $DIST_DIR
        env:
          DIST_DIR: ./dist/${{ matrix.tag }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./dist/${{ matrix.tag }}
          tags: capra314cabra/tex:${{ matrix.tag }}
          push: false
